<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="garry">
	
	<xacro:property name="base_x_len" value="17.0"/>
	<xacro:property name="base_y_len" value="25.0"/>
	<xacro:property name="base_z_len" value="0.4"/>

	<xacro:property name="board_y_back" value="3.5"/>
	<xacro:property name="board_x_len" value="7.0"/>
	<xacro:property name="board_y_len" value="9.0"/>
	<xacro:property name="board_z_len" value="15.0"/>
	<xacro:property name="board_y_origin" value="${-(base_y_len/2-board_y_back-board_y_len/2)}"/>

	<xacro:property name="wheel_d" value="5.4"/>
	<xacro:property name="wheel_th" value="1.8"/>
	<xacro:property name="wheel_y_origin" value="${board_y_origin}"/>
	<xacro:property name="wheel_x_origin" value="5.5"/>
	<xacro:property name="wheel_z_origin" value="${-wheel_d/2-1.5*base_z_len}"/> 

	<xacro:property name="gearbox_x_origin" value="2.6"/>
	<xacro:property name="gearbox_x_len" value="2.15"/>
	<xacro:property name="gearbox_z_len" value="4.2"/>
	<xacro:property name="gearbox_x_joint" value="${gearbox_x_origin+gearbox_x_len/2+wheel_th/2}"/>
	<xacro:property name="gearbox_z_origin" value="${-gearbox_z_len/2-base_z_len}"/>
	
	<xacro:property name="imu_x_origin" value="-4.0"/>
	<xacro:property name="imu_x_len" value="1.7"/>
	<xacro:property name="imu_y_len" value="2.2"/>
	<xacro:property name="imu_z_len" value="0.1"/>
	<xacro:property name="imu_yaw" value="${-pi/2}"/>

	<xacro:property name="raspi_cam_z_origin" value="15.0"/>

	<xacro:property name="webcam_x_origin" value="1.6"/>
	<xacro:property name="webcam_y_origin" value="${-(base_y_len/2-board_y_back)}"/>
	<xacro:property name="webcam_z_origin" value="${raspi_cam_z_origin}"/>

	<link name="base_link">
		<visual>
			<geometry>
				<box size="${base_x_len} ${base_y_len} ${base_z_len}"/>
			</geometry>
		</visual>
		<collision>
			<geometry>
				<box size="${base_x_len} ${base_y_len} ${base_z_len}"/>
			</geometry>
		</collision>
	</link>

	<link name="boards_link">
		<visual>
			<geometry>
				<box size="${board_x_len} ${board_y_len} ${board_z_len}"/>
			</geometry>
		</visual>
		<collision>
			<geometry>
				<box size="${board_x_len} ${board_y_len} ${board_z_len}"/>
			</geometry>
		</collision>
	</link>
	
	<joint name="base_to_board" type="fixed">
		<parent link="base_link"/>
		<child link="boards_link"/>
		<origin xyz="0.0 ${board_y_origin} ${board_z_len/2}"/>
	</joint>

	<link name="right_gearbox">
		<visual>
			<origin xyz="${gearbox_x_origin} ${wheel_y_origin} ${gearbox_z_origin}"/>
			<geometry>
				<box size="${gearbox_x_len} ${wheel_d} ${gearbox_z_len}"/>
			</geometry>
		</visual>
		<collision>
			<geometry>
				<box size="${gearbox_x_len} ${wheel_d} ${gearbox_z_len}"/>
			</geometry>
		</collision>
	</link>
	
	<link name="left_gearbox">
		<visual>
			<origin xyz="${-gearbox_x_origin} ${wheel_y_origin} ${gearbox_z_origin}"/>
			<geometry>
				<box size="${gearbox_x_len} ${wheel_d} ${gearbox_z_len}"/>
			</geometry>
		</visual>
		<collision>
			<geometry>
				<box size="${gearbox_x_len} ${wheel_d} ${gearbox_z_len}"/>
			</geometry>
		</collision>
	</link>

	<link name="right_wheel">
		<visual>
			<origin rpy="${pi/2} 0.0 ${pi/2} "/>
			<geometry>
				<cylinder length="${wheel_th}" radius="${wheel_d/2}"/>
			</geometry>
		</visual>
		<collision>
			<geometry>
				<cylinder length="${wheel_th}" radius="${wheel_d/2}"/>
			</geometry>
		</collision>
	</link>


	<link name="left_wheel">
		<visual>
			<origin rpy="${pi/2} 0.0 ${pi/2} "/>
			<geometry>
				<cylinder length="${wheel_th}" radius="${wheel_d/2}"/>
			</geometry>
		</visual>
		<collision>
			<geometry>
				<cylinder length="${wheel_th}" radius="${wheel_d/2}"/>
			</geometry>
		</collision>
	</link>
	
	<joint name="left_wheel_to_left_gearbox" type="fixed">
		<parent link="left_gearbox"/>
		<child link="left_wheel"/>
		<origin xyz="${-gearbox_x_joint} ${wheel_y_origin} ${wheel_z_origin}"/>
		<axis xyz="-1 0 0"/>
	</joint>

	<joint name="left_gearbox_to_base" type="fixed">
		<parent link="base_link"/>
		<child link="left_gearbox"/>
		<origin xyz="${-gearbox_x_origin} ${wheel_y_origin} ${base_z_len/2}"/>
	</joint>
	
	<joint name="right_wheel_to_right_gearbox" type="fixed">
		<parent link="right_gearbox"/>
		<child link="right_wheel"/>
		<origin xyz="${gearbox_x_joint} ${wheel_y_origin} ${wheel_z_origin}"/>
		<axis xyz="-1 0 0"/>
	</joint>

	<joint name="right_gearbox_to_base" type="fixed">
		<parent link="base_link"/>
		<child link="right_gearbox"/>
		<origin xyz="${gearbox_x_origin} ${wheel_y_origin} ${base_z_len/2}"/>
	</joint>
	
	<link name="imu_link">
		<visual>
			<geometry>
				<box size="${imu_x_len} ${imu_y_len} ${imu_z_len}"/>
			</geometry>
		</visual>
		<collision>
			<geometry>
				<box size="${imu_x_len} ${imu_y_len} ${imu_z_len}"/>
			</geometry>
		</collision>
	</link>

	<joint name="imu_to_base" type="fixed">
		<parent link="base_link"/>
		<child link="imu_link"/>
		<origin xyz="${imu_x_origin} ${wheel_y_origin} ${base_z_len/2}" rpy="0.0 0.0 ${imu_yaw}"/>
	</joint>
	
	<link name="webcam_link"/>
	<joint name="webcam_to_base" type="fixed">
		<parent link="base_link"/>
		<child link="webcam_link"/>
		<origin xyz="0.0 0.0 ${raspi_cam_z_origin}"/>
	</joint>
	
	<link name="raspicam_link"/>
	<joint name="raspicam_to_base" type="fixed">
		<parent link="base_link"/>
		<child link="raspicam_link"/>
		<origin xyz="${webcam_x_origin} ${webcam_y_origin} ${webcam_z_origin}"/>
	</joint>

</robot>
